services:
  postgres:
    image: postgres:16
    container_name: task_manager_db
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_password
      POSTGRES_DB: task_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U task_user -d task_db"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build:
      context: ./backend
    container_name: task_manager_backend
    environment:
      DATABASE_URL: postgresql://task_user:task_password@postgres:5432/task_db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
  frontend:
    build:
      context: ./frontend
    container_name: task_manager_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
volumes:
  postgres_data: