name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
        
      - name: Install frontend dependencies
        run: npm ci
      
      - name: Build frontend
        run: npm run build

  backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install backend dependencies
        run: pip install -r requirements.txt
  
  docker-backend:
    needs: backend
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Login to github container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend Docker image
        run: |
          docker build \
            -t ghcr.io/eranjaligoyal/task-manager-backend:${{ github.sha }} \
            -t ghcr.io/eranjaligoyal/task-manager-backend:latest \
            ./backend

      - name: Push backend Docker image
        run: |
          docker push ghcr.io/eranjaligoyal/task-manager-backend:${{ github.sha }}
          docker push ghcr.io/eranjaligoyal/task-manager-backend:latest

  deploy-backend:
    needs: docker-backend
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Render backend deploy
        run: curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"